services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: node ./dist/index.js
    depends_on:
      - multitor

  multitor:
    image: evait/multitor
    ports:
      - "9050-9059:9050-9059"
    env_file:
      - .env
    restart: always
